#taking inout from the user
name = input(" Enter your name: ")
bio = input("Enter the description: ")
email=input("Enter your email:")
phone= input("Enter your phone number:")
address=input("Enter your address:") 
headline = input("Enter your headline: ")
logo = input("Enter logo link: ")
image_url = input("Enter image URL: ")
resume_url = input("Enter resume URL: ")
#print the information
print("\n----- Resume Information -----")
print("Name:", name)
print("Bio:", bio)
print("Email:", email)
print("Phone:", phone)
print("Address:", address)
print("Headline:", headline)
print("Logo:", logo)
print("Image URL:", image_url)
print("Resume URL:", resume_url)